// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjVcqpGxkDBs9TDRFlPU96-8ckHNIrUaA',
    appId: '1:712081241407:web:871c122defb3d6e532cf8a',
    messagingSenderId: '712081241407',
    projectId: 'flutter-auth-cli',
    authDomain: 'flutter-auth-cli.firebaseapp.com',
    storageBucket: 'flutter-auth-cli.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkix7ogMo4Vb2GUyP0IgVmcRqga20JXao',
    appId: '1:712081241407:android:0b36a72d384dde8032cf8a',
    messagingSenderId: '712081241407',
    projectId: 'flutter-auth-cli',
    storageBucket: 'flutter-auth-cli.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYkHfoDcWgUSGHuU_Rh_hqwf6tos5i_iU',
    appId: '1:712081241407:ios:62e1a1f3351375fb32cf8a',
    messagingSenderId: '712081241407',
    projectId: 'flutter-auth-cli',
    storageBucket: 'flutter-auth-cli.appspot.com',
    iosBundleId: 'com.example.authicationFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYkHfoDcWgUSGHuU_Rh_hqwf6tos5i_iU',
    appId: '1:712081241407:ios:359daa3be2dab00e32cf8a',
    messagingSenderId: '712081241407',
    projectId: 'flutter-auth-cli',
    storageBucket: 'flutter-auth-cli.appspot.com',
    iosBundleId: 'com.example.authicationFirebase.RunnerTests',
  );
}
